{% set name = 'cpsr' %}
{% set version = os.environ.get('VERSION', '').replace('v.', '').replace('v', '') or '0.0.1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0

requirements:
  run:
    - pcgr >=0.8.4.10
    - r-upsetr
    - r-ggpubr

test:
  commands:
    - cpsr.py --version

about:
  home: https://github.com/sigven/cpsr
  license: MIT
  summary: Cancer Predisposition Sequencing Reporter (CPSR) - prioritization of germline variants in cancer

